#!/bin/python3 

import sys, os

"""
Collection of helper function to write subtraction terms
"""

############# from a subterm to a line ###################

def make_subterm(term_dict):
    subterm = ""
    for ant in term_dict["ant"]:
        subterm += ant + "*"
    subterm += term_dict["redme"] + "*"
    subterm += term_dict["jet"] #index still missing
    return subterm 

def make_subterms(term_dict_list):
    subterm_list = []
    for term_dict in term_dict_list:
        subterm_list.append(make_subterm(term_dict))
    return subterm_list

def add_indexes(subterm_list):
    new_subterm_list = []
    for idx, subterm in zip(range(1, len(subterm_list)+1, 1), subterm_list):
        subterm += "*a" + str(idx)
        new_subterm_list.append(subterm)
    return new_subterm_list 

######### from a list of subterms to a maple file #########

def write_header(fullme, outfile):
    f = open(outfile, "w")
    f.write("#Subtraction term autogenerated using the mapfrag library.\n")
    f.write("\n")
    f.write(fullme + "\n")
    f.write("\n")
    f.close()
    return None 

def write_subterms(subterm_list, outfile):
    f = open(outfile, "a")
    subterm_list = add_indexes(subterm_list)
    f.write("XX:=\n")
    f.write("\n")
    for subterm in subterm_list:
        f.write(subterm + "\n")
    f.write("\n")
    f.write(":")
    f.close()
    return None



